### ISSUE TITLE
Latest version is still 1.1.4 on atom packages

### ISSUE THREAD

**Issue by fernando-alves** [alexpls/rails-latest-migration-atom#8]
Hi

I tried installing this package but the listed version is still the old one. There was an old issue #5, with a similar problem but it seems that `package.json` has the correct version, so I don't know if something else is needed.

<img width="724" alt="rails-latest-migration-version" src="https://cloud.githubusercontent.com/assets/2341840/12698605/fd0c655a-c755-11e5-8da7-03d263231812.png">

For now I've installed from source, but it would be better to have the official version updated.

**Comment by alexpls** [comment]
Hi @fernando-alves, thanks for pointing this out!

Looks like the v1.1.5 release didn't get updated on the Atom Package Manager. To fix this I've tagged a new version (v1.1.6) and have verified that it shows up properly on APM.

This should let you install from inside the Atom Package Manager now rather than from source.

**Comment by fernando-alves** [comment]
Great, that worked. Thanks!
